import test from 'node:test';
import assert from 'node:assert/strict';
import { liftX86MachineEffects } from '../../../../js/targets/architecture/x86_64/effects/index.js';
import { decoded,mem,operations,reg } from './helpers.mjs';
function lift(input){const instruction=decoded(input),bundle=liftX86MachineEffects(instruction);assert.ok(bundle,`expected MachineEffects for ${input.family}`);return{instruction,bundle};}
const reads=(b)=>operations(b,'memory-read'),writes=(b)=>operations(b,'memory-write');
function assertAtomicPair(bundle){assert.equal(reads(bundle).length,1);assert.equal(writes(bundle).length,1);assert.equal(reads(bundle)[0].access.atomic,true);assert.equal(writes(bundle)[0].access.atomic,true);assert.equal(reads(bundle)[0].access.ordering,undefined);assert.equal(writes(bundle)[0].access.ordering,undefined);assert.deepEqual(reads(bundle)[0].access.addressExpr,writes(bundle)[0].access.addressExpr);assert.equal(reads(bundle)[0].metadata.rmwId,writes(bundle)[0].metadata.rmwId);}
test('LOCK ADD atomic without ordering overclaim',()=>{const{bundle}=lift({family:'add',prefixes:[0xf0],operands:[mem({base:'rax',widthBits:64,access:'read-write'}),reg('rbx',64,'read')]});assert.equal(bundle.completeness,'partial');assertAtomicPair(bundle);assert.equal(bundle.metadata.orderingMapping,'unmapped-not-seq-cst');assert.match(bundle.unknownEffects.reason,/ordering-not-representable/);});
test('memory XCHG implicit atomicity',()=>{const{bundle}=lift({family:'xchg',operands:[mem({base:'rax',widthBits:64,access:'read-write'}),reg('rcx',64,'read-write')]});assert.equal(bundle.completeness,'partial');assertAtomicPair(bundle);assert.equal(bundle.metadata.implicitAtomicWithoutLock,true);assert.equal(bundle.metadata.explicitLockPrefix,false);assert.ok(operations(bundle,'register-write').some((op)=>op.register.registerId==='rcx'));});
test('XADD without LOCK preserves old destination in source',()=>{const{bundle}=lift({family:'xadd',operands:[mem({base:'rax',widthBits:32,access:'read-write'}),reg('ecx',32,'read-write')]});assert.equal(reads(bundle)[0].access.atomic,false);assert.equal(writes(bundle)[0].access.atomic,false);assert.equal(bundle.metadata.sourceReceivesOldDestination,true);const sourceWrite=operations(bundle,'register-write').find((op)=>op.metadata.view==='ecx');assert.ok(sourceWrite);const transfer=operations(bundle,'value').find((op)=>op.opcode==='zext'&&op.metadata.fromBits===32&&op.metadata.toBits===64&&op.inputs?.[0]?.temporaryId===reads(bundle)[0].value.temporaryId);assert.ok(transfer);assert.deepEqual(sourceWrite.value,transfer.outputs[0]);assert.ok(operations(bundle,'flag-write').length>=6);});
test('LOCK XADD same-address atomic RMW',()=>{const{bundle}=lift({family:'xadd',prefixes:[0xf0],operands:[mem({base:'rdi',displacement:8n,widthBits:64,access:'read-write'}),reg('rax',64,'read-write')]});assert.equal(bundle.completeness,'partial');assertAtomicPair(bundle);assert.equal(bundle.metadata.sourceReceivesOldDestination,true);});
test('CMPXCHG success/failure contract is conditional',()=>{const{bundle}=lift({family:'cmpxchg',operands:[mem({base:'rdi',widthBits:64,access:'read-write'}),reg('rcx',64,'read')]});assert.equal(bundle.completeness,'partial');assert.equal(bundle.metadata.conditional,true);assert.equal(bundle.metadata.atomic,false);const success=operations(bundle,'value').find((op)=>op.metadata.semantic==='x86-cmpxchg-success'),memoryResult=operations(bundle,'value').find((op)=>op.metadata.semantic==='x86-cmpxchg-memory-result'),acc=operations(bundle,'value').find((op)=>op.metadata.semantic==='x86-cmpxchg-accumulator-result');assert.ok(success&&memoryResult&&acc);assert.equal(memoryResult.metadata.successPath,'source-to-destination');assert.equal(memoryResult.metadata.failurePath,'destination-unchanged');assert.equal(acc.metadata.failurePath,'old-destination-to-accumulator');assert.equal(writes(bundle)[0].metadata.conditionalWrite,true);assert.equal(writes(bundle)[0].metadata.failurePathArchitecturalWrite,false);assert.equal(writes(bundle)[0].metadata.representationIsConservativeMayWrite,true);});
test('LOCK CMPXCHG atomic but no fake seq-cst',()=>{const{bundle}=lift({family:'cmpxchg',prefixes:[0xf0],operands:[mem({base:'rdi',widthBits:32,access:'read-write'}),reg('ecx',32,'read')]});assert.equal(bundle.completeness,'partial');assertAtomicPair(bundle);assert.equal(bundle.metadata.orderingMapping,'unmapped-not-seq-cst');});
test('invalid LOCK register form not ignored',()=>{const{bundle}=lift({family:'add',prefixes:[0xf0],operands:[reg('rax',64,'read-write'),reg('rbx',64,'read')]});assert.equal(bundle.completeness,'partial');assert.equal(bundle.metadata.lockIgnored,false);assert.match(bundle.unknownEffects.reason,/lock-prefix-without-memory/);});
test('unsupported LOCK family remains conservative',()=>{const{bundle}=lift({family:'bts',prefixes:[0xf0],operands:[mem({base:'rax',widthBits:64,access:'read-write'}),reg('rcx',64,'read')]});assert.equal(bundle.completeness,'partial');assert.equal(bundle.metadata.lockIgnored,false);assert.match(bundle.unknownEffects.reason,/lock-prefixed-family-not-modelled/);});
test('atomic RMW identity and provenance survive',()=>{const{instruction,bundle}=lift({family:'xchg',operands:[reg('rax',64,'read-write'),mem({base:'rdi',index:'rcx',scale:8,displacement:-32n,widthBits:64,access:'read-write'})]});assertAtomicPair(bundle);assert.ok(bundle.origin.instructionIds.includes(instruction.instructionId));for(const op of bundle.operations)assert.equal(op.metadata.originInstructionId,instruction.instructionId);assert.equal(reads(bundle)[0].access.addressExpr.originInstructionId,instruction.instructionId);});
for(const family of ['cmpxchg8b','cmpxchg16b'])test(`${family}: wide atomic remains partial`,()=>{const widthBits=family==='cmpxchg16b'?128:64,{bundle}=lift({family,prefixes:[0xf0],operands:[mem({base:'rax',widthBits,access:'read-write'})]});assert.equal(bundle.completeness,'partial');assert.equal(bundle.unknownEffects.detail.expectedMemoryWidthBits,widthBits);assert.equal(bundle.metadata.exactWideAtomicClaim,false);if(family==='cmpxchg16b')assert.ok(bundle.possibleFaults.some((fault)=>fault.kind==='general-protection'));});
