from pathlib import Path

p = Path('js/interproc.js')
s = p.read_text()

marker = 'function simpleReturnExpression(value) {\n'
helper = '''function returnArgumentIndex(value) {\n  const source = transparentMoveSource(value);\n  if (!source) return null;\n  const origin = originOf(source);\n  const reg = source.kind === VK.ARG ? source.reg : origin?.kind === 'argument' ? origin.reg : null;\n  return /^x[0-7]$/.test(String(reg || '')) ? Number(String(reg).slice(1)) : null;\n}\n\n'''
if s.count(marker) != 1 or 'function returnArgumentIndex(value)' in s:
    raise SystemExit('returnArgumentIndex source shape mismatch')
s = s.replace(marker, helper + marker, 1)

old_expr = '''  const a = transparentMoveSource(aArg && aArg.value);\n  const b = transparentMoveSource(bArg && bArg.value);\n  if (!a || !b) return null;\n  const bits = Number(v.bits || v.def.extra?.dstBits || aArg?.bits || 64);\n  const signed = v.signed ?? null;\n  if (a.kind === VK.ARG && /^x[0-7]$/.test(String(a.reg || '')) && b.const != null) {\n    return { kind: 'argument-arithmetic', argument: Number(a.reg.slice(1)), op: v.def.sub, constant: b.const, bits, signed };\n  }\n  if (v.def.sub === 'add' && b.kind === VK.ARG && /^x[0-7]$/.test(String(b.reg || '')) && a.const != null) {\n    return { kind: 'argument-arithmetic', argument: Number(b.reg.slice(1)), op: 'add', constant: a.const, bits, signed };\n  }'''
new_expr = '''  const a = transparentMoveSource(aArg && aArg.value);\n  const b = transparentMoveSource(bArg && bArg.value);\n  if (!a || !b) return null;\n  const aArgument = returnArgumentIndex(a);\n  const bArgument = returnArgumentIndex(b);\n  const bits = Number(v.bits || v.def.extra?.dstBits || aArg?.bits || 64);\n  const signed = v.signed ?? null;\n  if (aArgument != null && b.const != null) {\n    return { kind: 'argument-arithmetic', argument: aArgument, op: v.def.sub, constant: b.const, bits, signed };\n  }\n  if (v.def.sub === 'add' && bArgument != null && a.const != null) {\n    return { kind: 'argument-arithmetic', argument: bArgument, op: 'add', constant: a.const, bits, signed };\n  }'''
if s.count(old_expr) != 1:
    raise SystemExit('simpleReturnExpression source shape mismatch')
s = s.replace(old_expr, new_expr, 1)

old_candidate = '''function summaryReturnCandidate(ir, ret) {\n  const explicit = ret?.args?.[0]?.value || null;\n  if (explicit) return { value: explicit, inferred: false };\n\n  // Untyped RET carries no x0 SSA use. A terminal x0 definition is useful as a\n  // local hint, but it is not an ABI return contract by itself.\n  const value = valueBefore(ir, ret, 'x0');\n  if (!value || value.kind === VK.ARG || !value.def) return { value: null, inferred: false };\n  if (value.def.row == null || ret.row == null || value.def.row >= ret.row) return { value: null, inferred: false };\n  const laterUse = (value.uses || []).some((use) => use !== ret && use.row != null && use.row > value.def.row && use.row < ret.row);\n  if (laterUse) return { value: null, inferred: false };\n  return { value, inferred: true };\n}'''
new_candidate = '''function weakTerminalCallReturn(ir, ret, calls) {\n  if (ret?.row == null) return null;\n  const candidates = (ir.instructions || []).filter((inst) => inst.op === OP.CALL\n    && inst.row != null && inst.row < ret.row\n    && (inst.block == null || ret.block == null || inst.block === ret.block));\n  const call = candidates.sort((a, b) => (b.row - a.row) || (b.id - a.id))[0] || null;\n  if (!call) return null;\n  const clobbers = call.clobbers || call.extra?.clobbers || [];\n  if (!clobbers.includes('x0')) return null;\n  const overwritten = (ir.instructions || []).some((inst) => inst !== call && inst !== ret\n    && inst.row != null && inst.row > call.row && inst.row < ret.row\n    && (inst.block == null || ret.block == null || inst.block === ret.block)\n    && (inst.dst?.reg === 'x0' || inst.extra?.publicStateIdentity === 'x0'));\n  if (overwritten) return null;\n  const metadata = (calls || []).find((item) => item.row === call.row) || null;\n  return {\n    kind: 'call',\n    target: metadata?.target ?? call.extra?.target ?? null,\n    instructionId: call.instructionId ?? call.id,\n    bits: call.returnBits || 64,\n    signed: null,\n  };\n}\n\nfunction passiveIncomingStateRead(value) {\n  if (!value?.def || value.def.op !== OP.MOV || !value.def.extra?.stateRead) return false;\n  const origin = originOf(value);\n  return origin?.kind === 'argument' || value.def.extra?.entryStateRead === true;\n}\n\nfunction summaryReturnCandidate(ir, ret, calls) {\n  const explicit = ret?.args?.[0]?.value || null;\n  if (explicit) return { value: explicit, descriptor: null, inferred: false };\n\n  // Untyped RET carries no x0 SSA use. A terminal x0 definition is useful as a\n  // local hint, but it is not an ABI return contract by itself. Compatibility\n  // may retain the legacy weak call-result view when the ABI marks x0 clobbered,\n  // without promoting an unknown call result to trusted semantic truth.\n  const value = valueBefore(ir, ret, 'x0');\n  if (!value || value.kind === VK.ARG || !value.def || passiveIncomingStateRead(value)) {\n    const descriptor = weakTerminalCallReturn(ir, ret, calls);\n    return descriptor ? { value: null, descriptor, inferred: true }\n      : { value: null, descriptor: null, inferred: false };\n  }\n  if (value.def.row == null || ret.row == null || value.def.row >= ret.row) return { value: null, descriptor: null, inferred: false };\n  const laterUse = (value.uses || []).some((use) => use !== ret && use.row != null && use.row > value.def.row && use.row < ret.row);\n  if (laterUse) return { value: null, descriptor: null, inferred: false };\n  return { value, descriptor: null, inferred: true };\n}'''
if s.count(old_candidate) != 1:
    raise SystemExit('summaryReturnCandidate source shape mismatch')
s = s.replace(old_candidate, new_candidate, 1)

old_use = '''    const candidate = summaryReturnCandidate(ir, ret);\n    const descriptor = returnDescriptor(candidate.value);'''
new_use = '''    const candidate = summaryReturnCandidate(ir, ret, calls);\n    const descriptor = candidate.descriptor || returnDescriptor(candidate.value);'''
if s.count(old_use) != 1:
    raise SystemExit('summaryReturnCandidate use source shape mismatch')
s = s.replace(old_use, new_use, 1)
p.write_text(s)
