from pathlib import Path

def rep(path, old, new):
    p = Path(path); text = p.read_text()
    if old not in text: raise SystemExit(f'missing block in {path}: {old[:90]!r}')
    p.write_text(text.replace(old, new, 1))

path='js/userscript/dev/parent-rpc.js'
rep(path,"  'dev.worker_pool.release',\n]);","  'dev.worker_pool.release',\n  'dev.taskgraph.create',\n  'dev.taskgraph.add',\n  'dev.taskgraph.replan',\n  'dev.taskgraph.start',\n  'dev.taskgraph.status',\n  'dev.taskgraph.await',\n  'dev.taskgraph.cancel',\n]);")
rep(path,"    poolRelease: (args = {}, opts = {}) => call('dev.worker_pool.release', args, opts),\n    close() {","    poolRelease: (args = {}, opts = {}) => call('dev.worker_pool.release', args, opts),\n    taskGraphCreate: (args = {}, opts = {}) => call('dev.taskgraph.create', args, opts),\n    taskGraphAdd: (args = {}, opts = {}) => call('dev.taskgraph.add', args, opts),\n    taskGraphReplan: (args = {}, opts = {}) => call('dev.taskgraph.replan', args, opts),\n    taskGraphStart: (args = {}, opts = {}) => call('dev.taskgraph.start', args, opts),\n    taskGraphStatus: (args = {}, opts = {}) => call('dev.taskgraph.status', args, opts),\n    taskGraphAwait: (args = {}, opts = {}) => call('dev.taskgraph.await', args, { ...opts, timeoutMs: 0 }),\n    taskGraphCancel: (args = {}, opts = {}) => call('dev.taskgraph.cancel', args, opts),\n    close() {")
rep(path,"  if (method === 'dev.worker_pool.release') return runtime.poolRelease(params, options);\n  throw rpcError('transport-failure', 'Unknown Dev parent RPC method.');","  if (method === 'dev.worker_pool.release') return runtime.poolRelease(params, options);\n  if (method === 'dev.taskgraph.create') return runtime.taskGraphCreate(params, options);\n  if (method === 'dev.taskgraph.add') return runtime.taskGraphAdd(params, options);\n  if (method === 'dev.taskgraph.replan') return runtime.taskGraphReplan(params, options);\n  if (method === 'dev.taskgraph.start') return runtime.taskGraphStart(params, options);\n  if (method === 'dev.taskgraph.status') return runtime.taskGraphStatus(params, options);\n  if (method === 'dev.taskgraph.await') return runtime.taskGraphAwait(params, options);\n  if (method === 'dev.taskgraph.cancel') return runtime.taskGraphCancel(params, options);\n  throw rpcError('transport-failure', 'Unknown Dev parent RPC method.');")

path='js/ai/dev/protocol/dev-supervisor-prompt.js'
rep(path,"    'Use worker.pool.start for independent tasks that should execute concurrently; poll/result and release leases only after completion. The pool maximum is six and a seventh claim waits for a released slot.',","    'Use worker.pool.start for independent tasks that should execute concurrently; poll/result and release leases only after completion. The pool maximum is six and a seventh claim waits for a released slot.',\n    'When taskgraph.* tools are present, prefer the task graph for multi-step engineering campaigns: encode dependencies explicitly, allow independent nodes to run in parallel, and use bounded retries with fresh Worker leases after recoverable Worker failure.',\n    'Task ownership/integrationHint fields are scheduling hints, not truth or permission. Verify repository/CI state independently before final claims.',")
rep(path,"    'Normal delegation sequence with the current single slot: worker.claim -> worker.create_chat -> worker.send.',","    'Legacy worker.* remains a one-slot compatibility lane. When worker.pool.* or taskgraph.* is available, do not serialize independent work through that legacy lane.',")
rep(path,"    'If a Worker exhausts a per-turn tool/execution window but the task is resumable, retain its result, release the slot, reclaim it, create a fresh Worker Chat, and hand off the continuation. Until multi-Worker is proven, only one Worker may be active at a time.',","    'If a Worker exhausts a per-turn tool/execution window but the task is resumable, retain its result and continue through a fresh Worker lease/chat. Respect the actual pool capacity returned by worker.pool.status; never invent extra slots.',")
rep(path,"    ['worker.pool.release', '{\"leaseId\":\"<returned lease id>\"}'],\n  ];","    ['worker.pool.release', '{\"leaseId\":\"<returned lease id>\"}'],\n    ['taskgraph.create', '{\"tasks\":[{\"id\":\"<task>\",\"instruction\":\"<instruction>\",\"dependsOn\":[],\"maxAttempts\":2,\"ownership\":[],\"integrationHint\":\"<optional>\"}]}'],\n    ['taskgraph.add', '{\"tasks\":[{\"id\":\"<task>\",\"instruction\":\"<instruction>\",\"dependsOn\":[\"<task>\"]}]}'],\n    ['taskgraph.replan', '{\"add\":[],\"cancel\":[\"<pending task id>\"]}'],\n    ['taskgraph.start', '{}'],\n    ['taskgraph.status', '{}'],\n    ['taskgraph.await', '{}'],\n    ['taskgraph.cancel', '{}'],\n  ];")

path='tests/userscript-release-version.mjs'
rep(path,"await import('./dev-agent/multi-worker-tab-pool.mjs');\nconsole.log('Userscript release-version contract passed');","await import('./dev-agent/multi-worker-tab-pool.mjs');\nawait import('./dev-agent/dynamic-task-graph.mjs');\nconsole.log('Userscript release-version contract passed');")

path='tests/userscript-dev-worker-runtime.mjs'
text=Path(path).read_text()
text=text.replace("assert.equal(runtime.mode, 'multi-tab-capable');","assert.equal(runtime.mode, 'task-graph-capable');")
Path(path).write_text(text)
