from pathlib import Path
import subprocess

def rep(path, old, new):
    p=Path(path); text=p.read_text()
    if old not in text: raise SystemExit(f'missing block: {path}: {old[:90]!r}')
    p.write_text(text.replace(old,new,1))

path='js/userscript/dev/parent-rpc.js'
rep(path,"  'dev.skill.run',\n]);","  'dev.skill.run',\n  'dev.worker_pool.status',\n  'dev.worker_pool.provision',\n  'dev.worker_pool.claim',\n  'dev.worker_pool.create_chat',\n  'dev.worker_pool.start',\n  'dev.worker_pool.observe',\n  'dev.worker_pool.result',\n  'dev.worker_pool.followup',\n  'dev.worker_pool.nudge',\n  'dev.worker_pool.stop',\n  'dev.worker_pool.release',\n]);")
rep(path,"    skillRun: (args = {}, opts = {}) => call('dev.skill.run', args, opts),\n    close() {","    skillRun: (args = {}, opts = {}) => call('dev.skill.run', args, opts),\n    poolStatus: (args = {}, opts = {}) => call('dev.worker_pool.status', args, opts),\n    poolProvision: (args = {}, opts = {}) => call('dev.worker_pool.provision', args, opts),\n    poolClaim: (args = {}, opts = {}) => call('dev.worker_pool.claim', args, opts),\n    poolCreateChat: (args = {}, opts = {}) => call('dev.worker_pool.create_chat', args, opts),\n    poolStart: (args = {}, opts = {}) => call('dev.worker_pool.start', args, opts),\n    poolObserve: (args = {}, opts = {}) => call('dev.worker_pool.observe', args, opts),\n    poolResult: (args = {}, opts = {}) => call('dev.worker_pool.result', args, opts),\n    poolFollowup: (args = {}, opts = {}) => call('dev.worker_pool.followup', args, opts),\n    poolNudge: (args = {}, opts = {}) => call('dev.worker_pool.nudge', args, opts),\n    poolStop: (args = {}, opts = {}) => call('dev.worker_pool.stop', args, opts),\n    poolRelease: (args = {}, opts = {}) => call('dev.worker_pool.release', args, opts),\n    close() {")
rep(path,"  if (method === 'dev.skill.run') return runtime.skillRun(params, options);\n  throw rpcError('transport-failure', 'Unknown Dev parent RPC method.');","  if (method === 'dev.skill.run') return runtime.skillRun(params, options);\n  if (method === 'dev.worker_pool.status') return runtime.poolStatus(params, options);\n  if (method === 'dev.worker_pool.provision') return runtime.poolProvision(params, options);\n  if (method === 'dev.worker_pool.claim') return runtime.poolClaim(params, options);\n  if (method === 'dev.worker_pool.create_chat') return runtime.poolCreateChat(params, options);\n  if (method === 'dev.worker_pool.start') return runtime.poolStart(params, options);\n  if (method === 'dev.worker_pool.observe') return runtime.poolObserve(params, options);\n  if (method === 'dev.worker_pool.result') return runtime.poolResult(params, options);\n  if (method === 'dev.worker_pool.followup') return runtime.poolFollowup(params, options);\n  if (method === 'dev.worker_pool.nudge') return runtime.poolNudge(params, options);\n  if (method === 'dev.worker_pool.stop') return runtime.poolStop(params, options);\n  if (method === 'dev.worker_pool.release') return runtime.poolRelease(params, options);\n  throw rpcError('transport-failure', 'Unknown Dev parent RPC method.');")

path='js/userscript/entry.js'
rep(path,"import { installDevBootstrapHost } from './dev/bootstrap-host.js';","import { installDevBootstrapHost } from './dev/bootstrap-host.js';\nimport { isDedicatedWorkerTab, startDedicatedWorkerTabRuntime } from './dev/tab-mesh/worker-tab-runtime.js';")
rep(path,"  cleanupPreviousSession();\n\n  const devWorkerRuntime = await startParentDevWorkerRuntime({","  if (isDedicatedWorkerTab(options.runtimeLocation || globalThis.location)) {\n    return startDedicatedWorkerTabRuntime({\n      location: options.runtimeLocation || globalThis.location,\n      document: globalThis.document,\n      history: globalThis.history,\n      BroadcastChannelRef: globalThis.BroadcastChannel,\n    });\n  }\n\n  cleanupPreviousSession();\n\n  const devWorkerRuntime = await startParentDevWorkerRuntime({")

path='js/ai/dev/protocol/dev-supervisor-prompt.js'
rep(path,"    'You may delegate implementation of a multi-tab/multi-Worker pool to the current Worker, but do not attempt to use unimplemented slots or invent tab identities.',","    'When worker.pool.* tools are present, the multi-Worker Tab Pool is installed. Use only leaseId/slot identities returned by those tools; never invent them.',\n    'worker.pool.provision may require browser permission to open tabs. If the browser explicitly blocks tab creation, report that exact blocker instead of pretending parallelism exists.',\n    'Use worker.pool.start for independent tasks that should execute concurrently; poll/result and release leases only after completion. The pool maximum is six and a seventh claim waits for a released slot.',")
rep(path,"    ['chatgpt.skill.run', '{\"skillId\":\"<skill id>\",\"program\":\"<program>\",\"args\":{}}'],\n  ];","    ['chatgpt.skill.run', '{\"skillId\":\"<skill id>\",\"program\":\"<program>\",\"args\":{}}'],\n    ['worker.pool.status', '{}'],\n    ['worker.pool.provision', '{\"size\":6,\"projectUrl\":\"<optional ChatGPT Project URL>\"}'],\n    ['worker.pool.claim', '{\"taskId\":\"<task id>\",\"wait\":true}'],\n    ['worker.pool.create_chat', '{\"leaseId\":\"<returned lease id>\"}'],\n    ['worker.pool.start', '{\"leaseId\":\"<returned lease id>\",\"instruction\":\"<specific task>\"}'],\n    ['worker.pool.observe', '{\"leaseId\":\"<returned lease id>\"}'],\n    ['worker.pool.result', '{\"leaseId\":\"<returned lease id>\"}'],\n    ['worker.pool.followup', '{\"leaseId\":\"<returned lease id>\",\"text\":\"<follow-up>\"}'],\n    ['worker.pool.nudge', '{\"leaseId\":\"<returned lease id>\"}'],\n    ['worker.pool.stop', '{\"leaseId\":\"<returned lease id>\"}'],\n    ['worker.pool.release', '{\"leaseId\":\"<returned lease id>\"}'],\n  ];")

path='scripts/build-userscript.mjs'
rep(path,"// @grant        GM.xmlHttpRequest\\n// @connect","// @grant        GM.xmlHttpRequest\\n// @grant        GM.openInTab\\n// @connect")

path='tests/userscript-release-version.mjs'
rep(path,"await import('./dev-agent/dom-skill-system.mjs');\nconsole.log('Userscript release-version contract passed');","await import('./dev-agent/dom-skill-system.mjs');\nawait import('./dev-agent/multi-worker-tab-pool.mjs');\nconsole.log('Userscript release-version contract passed');")

# Keep the established Round 2 regression intact and update only the intentional runtime contract changes.
path='tests/userscript-dev-worker-runtime.mjs'
subprocess.run(['git','checkout','origin/main','--',path], check=True)
rep(path,"assert.equal(runtime.mode, 'single-tab-conversation-worker');","assert.equal(runtime.mode, 'multi-tab-capable');")
rep(path,"assert.doesNotMatch(parentRuntimeSource, /BroadcastChannel|hex-worker=1|isManualWorkerTab/, 'active Round 2 runtime must not require another Safari tab');","assert.match(parentRuntimeSource, /MultiTabWorkerPool/, 'post-bootstrap parent runtime must expose the bounded multi-tab pool while retaining the single-tab compatibility lane');")
